In [34]:
import pandas as pd 
df =pd.read_csv('Blinkit_Dataset.csv')
print(df.head(10))

  Item Fat Content Item Identifier              Item Type  \
0          Regular           FDX32  Fruits and Vegetables
1          Low Fat           NCB42     Health and Hygiene
2          Regular           FDR28           Frozen Foods
3          Regular           FDL50                 Canned
4          Low Fat           DRI25            Soft Drinks
5          low fat           FDS52           Frozen Foods
6          Low Fat           NCU05     Health and Hygiene
7          Low Fat           NCD30              Household
8          Low Fat           FDW20  Fruits and Vegetables
9          Low Fat           FDX25                 Canned

   Outlet Establishment Year Outlet Identifier Outlet Location Type  \
0                       2012            OUT049               Tier 1
1                       2022            OUT018               Tier 3
2                       2016            OUT046               Tier 1
3                       2014            OUT013               Tier 3
4                       2015            OUT045               Tier 2
5                       2020            OUT017               Tier 2
6                       2011            OUT010               Tier 3
7                       2015            OUT045               Tier 2
8                       2014            OUT013               Tier 3
9                       2018            OUT027               Tier 3

  Outlet Size        Outlet Type  Item Visibility  Item Weight     Sales  \
0      Medium  Supermarket Type1         0.100014        15.10  145.4786
1      Medium  Supermarket Type2         0.008596        11.80  115.3492
2       Small  Supermarket Type1         0.025896        13.85  165.0210
3        High  Supermarket Type1         0.042278        12.15  126.5046
4       Small  Supermarket Type1         0.033970        19.60   55.1614
5       Small  Supermarket Type1         0.005505         8.89  102.4016
6       Small      Grocery Store         0.098312        11.80   81.4618
7       Small  Supermarket Type1         0.026904        19.70   96.0726
8        High  Supermarket Type1         0.024129        20.75  124.1730
9      Medium  Supermarket Type3         0.101562          NaN  181.9292

   Rating
0     5.0
1     5.0
2     5.0
3     5.0
4     5.0
5     5.0
6     5.0
7     5.0
8     5.0
9     5.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           8523 non-null   object
 1   Item Identifier            8523 non-null   object
 2   Item Type                  8523 non-null   object
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Identifier          8523 non-null   object
 5   Outlet Location Type       8523 non-null   object
 6   Outlet Size                8523 non-null   object
 7   Outlet Type                8523 non-null   object
 8   Item Visibility            8523 non-null   float64
 9   Item Weight                7060 non-null   float64
 10  Sales                      8523 non-null   float64
 11  Rating                     8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [36]:
df.describe()

,Outlet Establishment Year,Item Visibility,Item Weight,Sales,Rating
count,8523.000000,8523.000000,7060.000000,8523.000000,8523.000000
mean,2016.450546,0.066132,12.857645,140.992783,3.965857
std,3.189396,0.051598,4.643456,62.275067,0.605651
min,2011.000000,0.000000,4.555000,31.290000,1.000000
25%,2014.000000,0.026989,8.773750,93.826500,4.000000
50%,2016.000000,0.053931,12.600000,143.012800,4.000000
75%,2018.000000,0.094585,16.850000,185.643700,4.200000
max,2022.000000,0.328391,21.350000,266.888400,5.000000

In [37]:
df.isnull().sum()

Item Fat Content                0
Item Identifier                 0
Item Type                       0
Outlet Establishment Year       0
Outlet Identifier               0
Outlet Location Type            0
Outlet Size                     0
Outlet Type                     0
Item Visibility                 0
Item Weight                  1463
Sales                           0
Rating                          0
dtype: int64

In [38]:
df['Item Weight']=df['Item Weight'].fillna(df['Item Weight'].mean())
print(df)

     Item Fat Content Item Identifier              Item Type  \
0             Regular           FDX32  Fruits and Vegetables
1             Low Fat           NCB42     Health and Hygiene
2             Regular           FDR28           Frozen Foods
3             Regular           FDL50                 Canned
4             Low Fat           DRI25            Soft Drinks
...               ...             ...                    ...
8518          low fat           NCT53     Health and Hygiene
8519          low fat           FDN09            Snack Foods
8520          low fat           DRE13            Soft Drinks
8521              reg           FDT50                  Dairy
8522              reg           FDM58            Snack Foods

      Outlet Establishment Year Outlet Identifier Outlet Location Type  \
0                          2012            OUT049               Tier 1
1                          2022            OUT018               Tier 3
2                          2016            OUT046               Tier 1
3                          2014            OUT013               Tier 3
4                          2015            OUT045               Tier 2
...                         ...               ...                  ...
8518                       2018            OUT027               Tier 3
8519                       2018            OUT027               Tier 3
8520                       2018            OUT027               Tier 3
8521                       2018            OUT027               Tier 3
8522                       2018            OUT027               Tier 3

     Outlet Size        Outlet Type  Item Visibility  Item Weight     Sales  \
0         Medium  Supermarket Type1         0.100014    15.100000  145.4786
1         Medium  Supermarket Type2         0.008596    11.800000  115.3492
2          Small  Supermarket Type1         0.025896    13.850000  165.0210
3           High  Supermarket Type1         0.042278    12.150000  126.5046
4          Small  Supermarket Type1         0.033970    19.600000   55.1614
...          ...                ...              ...          ...       ...
8518      Medium  Supermarket Type3         0.000000    12.857645  164.5526
8519      Medium  Supermarket Type3         0.034706    12.857645  241.6828
8520      Medium  Supermarket Type3         0.027571    12.857645   86.6198
8521      Medium  Supermarket Type3         0.107715    12.857645   97.8752
8522      Medium  Supermarket Type3         0.000000    12.857645  112.2544

      Rating
0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
...      ...
8518     4.0
8519     4.0
8520     4.0
8521     4.0
8522     4.0

[8523 rows x 12 columns]

In [39]:
df.isnull().sum()

Item Fat Content             0
Item Identifier              0
Item Type                    0
Outlet Establishment Year    0
Outlet Identifier            0
Outlet Location Type         0
Outlet Size                  0
Outlet Type                  0
Item Visibility              0
Item Weight                  0
Sales                        0
Rating                       0
dtype: int64

In [40]:
df.columns.all()
df

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,low fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,low fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,low fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,reg,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,reg,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [41]:
print(df['Outlet Identifier'].dtype)

object

In [42]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8518    False
8519    False
8520    False
8521    False
8522    False
Length: 8523, dtype: bool

In [48]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [50]:
df.columns.all()
df

,item_fat_content,item_identifier,item_type,outlet_establishment_year,outlet_identifier,outlet_location_type,outlet_size,outlet_type,item_visibility,item_weight,sales,rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,low fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,low fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,low fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,reg,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,reg,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [51]:
df.to_csv('Blinkit_Dataset(clean).csv')

In [53]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = "Souvik@123"
host = "localhost"
port = "5432"
database = "Blinkit"

encoded_password = quote_plus(password)

engine = create_engine(
    f"postgresql+psycopg2://{username}:{encoded_password}@{host}:{port}/{database}"
)

table_name = "blinkit_data"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'blinkit_data' in database 'Blinkit'.